version: '3'
services:
  db:
    build:
      context: ""
      dockerfile: db.dockerfile
    container_name: db-transfer
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - transfer-dev
networks:
  transfer-dev: