#!/bin/sh
set -e

echo "Creating user: ${POSTGRES_USER} ..."
$POSTGRES <<EOSQL
CREATE USER ${POSTGRES_USER} WITH SUPERUSER PASSWORD ${POSTGRES_PASSWORD};
COMMIT;
EOSQL

echo "Creating database: ${POSTGRES_DB} ..."
$POSTGRES <<EOSQL
CREATE DATABASE ${POSTGRES_DB};
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
COMMIT;
EOSQL

echo "Creating schema: ${POSTGRES_SCHEMA} ..."
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" --command "CREATE SCHEMA ${POSTGRES_SCHEMA}; GRANT ALL PRIVILEGES ON SCHEMA ${POSTGRES_SCHEMA} TO ${POSTGRES_USER};"